services:
  - type: web
    name: pulsetrack
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn serverMonitoring.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsetrack-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3