# Generated by Django 5.1.4 on 2024-12-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('check_interval', models.IntegerField(choices=[(30, 'Every 30 seconds'), (60, 'Every minute'), (300, 'Every 5 minutes'), (600, 'Every 10 minutes')], default=30, verbose_name='Check Interval')),
                ('response_timeout', models.PositiveIntegerField(default=5, verbose_name='Response Timeout (seconds)')),
                ('log_retention_days', models.PositiveIntegerField(default=7, verbose_name='Log Retention (days)')),
                ('alert_threshold', models.PositiveIntegerField(default=90, verbose_name='Alert Threshold (%)')),
                ('notification_cooldown', models.PositiveIntegerField(default=300, verbose_name='Notification Cooldown (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Configuration',
                'verbose_name_plural': 'User Configurations',
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['username'], name='user_usermo_usernam_55e02e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['email'], name='user_usermo_email_65e21b_idx'),
        ),
        migrations.AddIndex(
            model_name='userconfig',
            index=models.Index(fields=['user'], name='user_userco_user_id_856c97_idx'),
        ),
    ]
